import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { type AppType } from "next/app";
import { Inter } from "next/font/google";
import { api } from "~/utils/api";
import "~/styles/globals.css";
import Head from "next/head";
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`vignette flex w-screen h-screen min-h-screen items-center bg-[url('/assets/background_table_tiled_small.webp')] bg-repeat justify-center font-sans ${inter.variable}`}>
            <Component {...pageProps} />
            <SpeedInsights />
      </main>

    

      {/* <main className={`flex min-h-screen items-center justify-center bg-[url('/assets/background_table_tiled_small.jpg')] bg-repeat font-sans ${inter.variable}`}>
          <div className="container flex items-center justify-center"> 
            <Component {...pageProps} />
          </div>
      </main> */}

    </SessionProvider>
    
  );
};

export default api.withTRPC(MyApp);
