import Head from "next/head";
import {
  HandComponent,
  BattleAreaComponent,
  DeckAreaComponent,
} from "~/components";
import {
  CardModel,
  HandModel,
  PairModel,
  BattleAreaModel,
  DeckModel,
  Suits,
  Ranks,
} from "~/game-logic";

const testHand: HandModel = {
  cards: [
    {
      suit: "♦",
      rank: 11,
    },
    {
      suit: "♥",
      rank: 6,
    },
    {
      suit: "♣",
      rank: 13,
    },
    {
      suit: "♠",
      rank: 10,
    },
    {
      suit: "♦",
      rank: 8,
    },
    {
      suit: "♥",
      rank: 7,
    },
    {
      suit: "♣",
      rank: 12,
    },
    {
      suit: "♠",
      rank: 14,
    },
  ],
};

// const testCard1:CardModel = testHand.cards[0];

const testPair1: PairModel = {
  attack: {
    suit: "♦",
    rank: 11,
  },
  defence: {
    suit: "♥",
    rank: 6,
  },
};

const testPair2: PairModel = {
  attack: {
    suit: "♣",
    rank: 13,
  },
  defence: {
    suit: "♠",
    rank: 10,
  },
};

const testPair3: PairModel = {
  attack: {
    suit: "♦",
    rank: 11,
  },
};

const testBattleArea: BattleAreaModel = {
  pairs: [testPair1, testPair2, testPair3],
};

function createDeck(): DeckModel {
  let cards = [];

  for (let suit of Suits) {
    for (let rank of Ranks) {
      cards.push({ suit: suit, rank: rank });
    }
  }
  return { cards: cards, trumpCard: cards[0]! };
}

const testDeck = createDeck();

const testDeck2: DeckModel = {
  cards: [],
  trumpCard: {
    suit: "♦",
    rank: 11,
  },
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-repeat] flex min-h-screen flex-row items-center justify-center bg-[url('/assets/background_table_tiled_small.jpg')]">
        {/* bg-gradient-to-b from-[#306e3a] to-[#0e2211 */}
        <div className="container flex flex-row items-center justify-center gap-3">
          <DeckAreaComponent className="pr-28" deck={testDeck2} />

          <div className="flex flex-col">
            <HandComponent hand={testHand} isPlayer={false} />
            <BattleAreaComponent
              className="py-14"
              battleArea={testBattleArea}
            />
            <HandComponent hand={testHand} isPlayer={true} />
          </div>

          <DeckAreaComponent className="pl-12" deck={testDeck} />
        </div>
      </main>
    </>
  );
}
